apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-devops-lab
  labels:
    app: nest-devops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-devops-lab
  template:
    metadata:
      labels:
        app: nest-devops-lab
    spec:
      containers:
        - name: nest-devops-lab
          image: nest-devops-lab:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"