apiVersion: v1
kind: Service
metadata:
  name: nest-devops-lab
  labels:
    app: nest-devops-lab
spec:
  type: NodePort
  selector:
    app: nest-devops-lab
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080